import axios from 'axios';

const API_URL = (import.meta as any).env?.VITE_API_URL || '/api';

// Types & Interfaces
export interface User {
  _id: string;
  id: string;
  email: string;
  username: string;
  role: 'user' | 'admin';
  accountType?: 'standard' | 'tipster' | 'wildcard';
  isPro: boolean;
  isCertified?: boolean;
  walletBalance: number;
  avatar: string;
  password?: string;
}

export interface Transaction {
  _id: string;
  id: string;
  user: string;
  amount: number;
  type: 'recharge' | 'withdrawal' | 'subscription' | 'pro' | 'product';
  status: 'pending' | 'completed' | 'failed';
  createdAt: string;
}

export interface Reply {
  id: string | number;
  user: string;
  avatar: string;
  text: string;
  time: string;
  likes: number;
  likedBy: (string | number)[];
}

export interface DebateMessage {
  id: string | number;
  author: string;
  authorId: string;
  user: string;
  avatar: string;
  text: string;
  timestamp: string;
  time: string;
  likes: number;
  likedBy: (string | number)[];
  replies: Reply[];
}

export type Message = DebateMessage;

export interface Debate {
  _id: string;
  id: string | number;
  title: string;
  description: string;
  images: string[];
  category: string;
  participants: number;
  lastActivity: string;
  author: { id: string | number, username: string, avatar: string };
  authorId: string;
  likes: number;
  likedBy: (string | number)[];
  messages: DebateMessage[];
  createdAt: string;
  // News-sourced debate fields
  sourceArticle?: {
    articleId: string;
    title: string;
    link: string;
    source: string;
    image: string;
  };
  isAutoGenerated?: boolean;
  isFavorite?: boolean;
  favoritedBy?: (string | number)[];
  expiresAt?: string | null;
}

// Axios instance configuration
const api = axios.create({
  baseURL: API_URL,
  headers: {
    'Content-Type': 'application/json'
  },
  timeout: 10000
});

// Request interceptor for adding auth token
api.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('token');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => Promise.reject(error)
);

// Response interceptor to handle connection errors and switch to fallback

const transformUploadUrls = (obj: any): any => {
  if (obj === null || obj === undefined) return obj;
  if (typeof obj === 'string') {
    if (obj.startsWith('/uploads/')) {
      const apiURL = (import.meta as any).env?.VITE_API_URL || '/api';
      const cleanApiURL = apiURL.endsWith('/') ? apiURL.slice(0, -1) : apiURL;
      const cleanObj = obj.startsWith('/') ? obj : `/${obj}`;
      // This will map /uploads/xxx to /api/uploads/xxx (or http://domain/api/uploads/xxx)
      // which is correctly served by the backend proxy.
      return `${cleanApiURL}${cleanObj}`;
    }
    return obj;
  }
  if (Array.isArray(obj)) {
    return obj.map(transformUploadUrls);
  }
  if (typeof obj === 'object') {
    const newObj: any = {};
    for (const key in obj) {
      newObj[key] = transformUploadUrls(obj[key]);
    }
    return newObj;
  }
  return obj;
};

const normalizeIds = (obj: any): any => {
  if (obj === null || obj === undefined) return obj;
  if (obj instanceof Date) return obj;

  if (Array.isArray(obj)) {
    return obj.map(normalizeIds);
  }

  if (typeof obj === 'object') {
    if (obj._id && !obj.id) {
      obj.id = String(obj._id);
    }
    for (const key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        obj[key] = normalizeIds(obj[key]);
      }
    }
  }
  return obj;
};

api.interceptors.response.use(
  (response) => {
    if (response.data) {
      response.data = normalizeIds(transformUploadUrls(response.data));
    }
    return response;
  },
  (error) => {
    if (error.code === 'ECONNREFUSED' || error.code === 'ECONNABORTED' || !error.response) {
      console.log('API Connection failed - using fallback mode');
      localStorage.setItem('fallbackMode', 'true');
    }
    return Promise.reject(error);
  }
);

// --- Auth Services ---
export const register = async (userData: any) => {
  try {
    const response = await api.post('/auth/register', userData);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const newUser = {
        id: Date.now().toString(),
        ...userData,
        role: 'user',
        accountType: userData.accountType || 'standard',
        isPro: userData.accountType === 'tipster',
        walletBalance: 0,
        avatar: ''
      };
      localStorage.setItem('fallbackUser', JSON.stringify(newUser));
      return { token: 'mock-token', user: newUser };
    }
    throw error;
  }
};

export const login = async (credentials: any) => {
  try {
    const response = await api.post('/auth/login', credentials);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      // Basic mock login for testing
      const mockUser: User = {
        _id: 'mock-id',
        id: 'mock-id',
        email: credentials.email,
        username: credentials.email.split('@')[0],
        role: credentials.email.includes('admin') ? 'admin' : 'user',
        isPro: credentials.email.includes('pro'),
        walletBalance: 100,
        avatar: ''
      };
      localStorage.setItem('fallbackUser', JSON.stringify(mockUser));
      return { token: 'mock-token', user: mockUser };
    }
    throw error;
  }
};

export const googleLogin = async (credential: string, accountType?: string) => {
  try {
    const response = await api.post('/auth/google', { credential, accountType });
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const mockUser: User = {
        _id: 'mock-google-id',
        id: 'mock-google-id',
        email: 'google-user@example.com',
        username: 'google_user',
        role: 'user',
        accountType: (accountType as any) || 'standard',
        isPro: accountType === 'tipster',
        isCertified: false,
        walletBalance: 0,
        avatar: 'https://lh3.googleusercontent.com/a/default-user'
      };
      localStorage.setItem('fallbackUser', JSON.stringify(mockUser));
      return { token: 'mock-token', user: mockUser };
    }
    throw error;
  }
};

export const upgradeUserRole = async (targetRole: 'tipster') => {
  const response = await api.post('/users/upgrade-role', { targetRole });
  return response.data;
};

export const getCurrentUser = async () => {
  try {
    const response = await api.get('/users/me');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('fallbackUser') || 'null');
    }
    throw error;
  }
};

export const updateUser = async (updates: any) => {
  try {
    const response = await api.put('/users/me', updates);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const user = JSON.parse(localStorage.getItem('fallbackUser') || '{}');
      const updatedUser = { ...user, ...updates };
      localStorage.setItem('fallbackUser', JSON.stringify(updatedUser));
      return updatedUser;
    }
    throw error;
  }
};

// --- Admin Services ---
export const getUsers = async () => {
  try {
    const response = await api.get('/admin/users');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('pronobox_users') || '[]');
    }
    throw error;
  }
};

export const updateUserByAdmin = async (userId: string, updates: any) => {
  try {
    const response = await api.put(`/admin/users/${userId}`, updates);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const users = JSON.parse(localStorage.getItem('pronobox_users') || '[]');
      const index = users.findIndex((u: any) => u.id === userId);
      if (index !== -1) {
        users[index] = { ...users[index], ...updates };
        localStorage.setItem('pronobox_users', JSON.stringify(users));
        return users[index];
      }
      throw new Error('User not found');
    }
    throw error;
  }
};

export const getAdminTransactions = async () => {
  try {
    const response = await api.get('/admin/transactions');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('pronobox_admin_transactions') || '[]');
    }
    throw error;
  }
};

export const getAdminWithdrawals = async () => {
  try {
    const response = await api.get('/admin/withdrawals');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('pronobox_admin_withdrawals') || '[]');
    }
    throw error;
  }
};

export const getSupportMessages = async () => {
  try {
    const response = await api.get('/admin/support/messages');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('pronobox_support_messages') || '[]');
    }
    throw error;
  }
};

export const updateWithdrawalStatus = async (id: string, status: string) => {
  try {
    const response = await api.put(`/admin/withdrawals/${id}/status`, { status });
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const withdrawals = JSON.parse(localStorage.getItem('pronobox_admin_withdrawals') || '[]');
      const index = withdrawals.findIndex((w: any) => w.id === id);
      if (index !== -1) {
        withdrawals[index].status = status;
        localStorage.setItem('pronobox_admin_withdrawals', JSON.stringify(withdrawals));
        return withdrawals[index];
      }
      throw new Error('Withdrawal not found');
    }
    throw error;
  }
};

export const sendAdminSupportMessage = async (data: any) => {
  try {
    const response = await api.post('/admin/support/send', data);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const messages = JSON.parse(localStorage.getItem('pronobox_support_messages') || '[]');
      const newMessage = { id: Date.now(), ...data, sender: 'agent', time: new Date().toLocaleTimeString() };
      messages.push(newMessage);
      localStorage.setItem('pronobox_support_messages', JSON.stringify(messages));
      return newMessage;
    }
    throw error;
  }
};

// --- Transaction Services ---
export const createTransaction = async (data: any) => {
  try {
    const response = await api.post('/transactions', data);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const transactions = JSON.parse(localStorage.getItem('pronobox_transactions') || '[]');
      const newTransaction = { id: `tr-${Date.now()}`, ...data, status: 'completed', createdAt: new Date().toISOString() };
      transactions.push(newTransaction);
      localStorage.setItem('pronobox_transactions', JSON.stringify(transactions));
      return newTransaction;
    }
    throw error;
  }
};

export const getTransactions = async () => {
  try {
    const response = await api.get('/transactions');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('pronobox_transactions') || '[]');
    }
    throw error;
  }
};

// --- Channel Services ---
export const getChannels = async () => {
  try {
    const response = await api.get('/channels');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('pronobox_channels') || '[]');
    }
    throw error;
  }
};

export const getChannel = async (id: string | number) => {
  try {
    const response = await api.get(`/channels/${id}`);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const channels = JSON.parse(localStorage.getItem('pronobox_channels') || '[]');
      return channels.find((c: any) => String(c.id) === String(id));
    }
    throw error;
  }
};

export const createChannel = async (data: any) => {
  try {
    const response = await api.post('/channels', data);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const channels = JSON.parse(localStorage.getItem('pronobox_channels') || '[]');
      const newChannel = { id: `ch-${Date.now()}`, ...data, members: 1, createdAt: new Date().toISOString() };
      channels.push(newChannel);
      localStorage.setItem('pronobox_channels', JSON.stringify(channels));
      return newChannel;
    }
    throw error;
  }
};

export const updateChannel = async (id: string | number, data: any) => {
  try {
    const response = await api.put(`/channels/${id}`, data);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const channels = JSON.parse(localStorage.getItem('pronobox_channels') || '[]');
      const index = channels.findIndex((c: any) => String(c.id) === String(id));
      if (index !== -1) {
        channels[index] = { ...channels[index], ...data };
        localStorage.setItem('pronobox_channels', JSON.stringify(channels));
        return channels[index];
      }
    }
    throw error;
  }
};

export const deleteChannel = async (id: string | number) => {
  try {
    await api.delete(`/channels/${id}`);
    return true;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const channels = JSON.parse(localStorage.getItem('pronobox_channels') || '[]');
      const filtered = channels.filter((c: any) => String(c.id) !== String(id));
      localStorage.setItem('pronobox_channels', JSON.stringify(filtered));
      return true;
    }
    throw error;
  }
};

export const joinChannel = async (id: string | number) => {
  // Always persist locally — compact {channelId: memberIds[]} format
  const persistJoin = () => {
    try {
      const membership: Record<string, string[]> = JSON.parse(localStorage.getItem('pronobox_membership') || '{}');
      const user = JSON.parse(localStorage.getItem('user') || localStorage.getItem('fallbackUser') || 'null');
      const userId = user?.id ? String(user.id) : null;
      if (userId) {
        const channelKey = String(id);
        const members = membership[channelKey] || [];
        if (!members.includes(userId)) {
          membership[channelKey] = [...members, userId];
          localStorage.setItem('pronobox_membership', JSON.stringify(membership));
        }
      }
    } catch { /* quota or parse error — skip */ }
  };

  try {
    const response = await api.post(`/channels/${id}/join`);
    persistJoin();
    return response.data;
  } catch (error) {
    persistJoin(); // Still persist locally even if backend fails
    return { success: true };
  }
};

export const leaveChannel = async (id: string | number) => {
  // Always remove from local membership cache
  const persistLeave = () => {
    try {
      const membership: Record<string, string[]> = JSON.parse(localStorage.getItem('pronobox_membership') || '{}');
      const user = JSON.parse(localStorage.getItem('user') || localStorage.getItem('fallbackUser') || 'null');
      const userId = user?.id ? String(user.id) : null;
      if (userId) {
        const channelKey = String(id);
        membership[channelKey] = (membership[channelKey] || []).filter(uid => uid !== userId);
        localStorage.setItem('pronobox_membership', JSON.stringify(membership));
      }
    } catch { /* quota or parse error — skip */ }
  };

  try {
    const response = await api.post(`/channels/${id}/leave`);
    persistLeave();
    return response.data;
  } catch (error) {
    persistLeave(); // Still remove locally even if backend fails
    return { success: true };
  }
};

export const uploadMedia = async (file: File | Blob) => {
  try {
    const formData = new FormData();
    if (file instanceof Blob && !(file instanceof File)) {
      const mime = file.type || '';
      let extension = 'bin';
      if (mime.includes('/')) {
        extension = mime.split('/')[1];
      }
      formData.append('media', file, `voice-message.${extension}`);
    } else {
      formData.append('media', file);
    }
    const response = await api.post('/upload-media', formData, {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
    });
    return response.data; // Expected { url: '/uploads/filename.ext' }
  } catch (error) {
    console.error('Failed to upload media', error);
    throw error;
  }
};

export const sendMessage = async (channelId: string | number, text: string, imageUrl?: string | null, audioUrl?: string | null, isImage?: boolean, isVoiceMessage?: boolean, replyTo?: any) => {
  try {
    const payload: any = { text };
    if (imageUrl) payload.imageUrl = imageUrl;
    if (audioUrl) payload.audioUrl = audioUrl;
    if (isImage !== undefined) payload.isImage = isImage;
    if (isVoiceMessage !== undefined) payload.isVoiceMessage = isVoiceMessage;
    if (replyTo) payload.replyTo = replyTo;
    
    const response = await api.post(`/channels/${channelId}/messages`, payload);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return { id: Date.now(), text, time: new Date().toLocaleTimeString(), sender: 'me' };
    }
    throw error;
  }
};

export const deleteChannelMessage = async (channelId: string, messageId: string) => {
  try {
    const response = await api.delete(`/channels/${channelId}/messages/${messageId}`);
    return response.data;
  } catch (error) {
    console.error('API Error:', error);
    throw error;
  }
};

// --- Debate Services ---
export const getDebates = async () => {
  try {
    const response = await api.get('/debates');
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      return JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
    }
    throw error;
  }
};

export const createDebate = async (data: any) => {
  try {
    const response = await api.post('/debates', data);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const user = JSON.parse(localStorage.getItem('fallbackUser') || 'null');
      const newDebate: Debate = {
        _id: `mock-${Date.now()}`,
        id: Date.now(),
        ...data,
        participants: 1,
        lastActivity: "À l'instant",
        author: { id: user?.id || 'unknown', username: user?.username || 'Anonyme', avatar: user?.avatar || '' },
        authorId: user?.id || 'unknown',
        likes: 0,
        likedBy: [],
        messages: [],
        createdAt: new Date().toISOString()
      };
      debates.push(newDebate);
      localStorage.setItem('pronobox_debates', JSON.stringify(debates));
      return newDebate;
    }
    throw error;
  }
};

export const updateDebate = async (id: string | number, updates: any) => {
  try {
    const response = await api.put(`/debates/${id}`, updates);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const index = debates.findIndex((d: Debate) => String(d.id) === String(id));
      if (index !== -1) {
        debates[index] = { ...debates[index], ...updates };
        localStorage.setItem('pronobox_debates', JSON.stringify(debates));
        return debates[index];
      }
      throw new Error('Debate not found');
    }
    throw error;
  }
};

export const deleteDebate = async (id: string | number) => {
  try {
    await api.delete(`/debates/${id}`);
    return true;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const filtered = debates.filter((d: Debate) => String(d.id) !== String(id));
      localStorage.setItem('pronobox_debates', JSON.stringify(filtered));
      return true;
    }
    throw error;
  }
};

export const likeDebate = async (id: string | number) => {
  try {
    const response = await api.post(`/debates/${id}/like`);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const user = JSON.parse(localStorage.getItem('fallbackUser') || 'null');
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const index = debates.findIndex((d: Debate) => String(d.id) === String(id));
      if (index !== -1) {
        const debate = debates[index];
        const userLiked = debate.likedBy.some((lid: any) => String(lid) === String(user?.id));
        if (userLiked) {
          debate.likedBy = debate.likedBy.filter((lid: any) => String(lid) !== String(user?.id));
          debate.likes = Math.max(0, debate.likes - 1);
        } else {
          debate.likedBy.push(user?.id);
          debate.likes += 1;
        }
        localStorage.setItem('pronobox_debates', JSON.stringify(debates));
        return debate;
      }
      throw new Error('Debate not found');
    }
    throw error;
  }
};

export const addDebateMessage = async (debateId: string | number, text: string) => {
  try {
    const response = await api.post(`/debates/${debateId}/messages`, { text });
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const user = JSON.parse(localStorage.getItem('fallbackUser') || 'null');
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const index = debates.findIndex((d: Debate) => String(d.id) === String(debateId));
      if (index !== -1) {
        const newMessage: DebateMessage = {
          id: Date.now(),
          author: user?.username || 'Anonyme',
          authorId: user?.id || 'unknown',
          user: user?.username || 'Anonyme',
          avatar: user?.avatar || '',
          text,
          timestamp: new Date().toISOString(),
          time: "À l'instant",
          likes: 0,
          likedBy: [],
          replies: []
        };
        debates[index].messages.push(newMessage);
        localStorage.setItem('pronobox_debates', JSON.stringify(debates));
        return debates[index];
      }
      throw new Error('Debate not found');
    }
    throw error;
  }
};

export const addDebateReply = async (debateId: string | number, messageId: string | number, text: string) => {
  try {
    const response = await api.post(`/debates/${debateId}/messages/${messageId}/replies`, { text });
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const user = JSON.parse(localStorage.getItem('fallbackUser') || 'null');
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const index = debates.findIndex((d: Debate) => String(d.id) === String(debateId));
      if (index !== -1) {
        const msgIndex = debates[index].messages.findIndex((m: any) => String(m.id) === String(messageId));
        if (msgIndex !== -1) {
          const newReply: Reply = {
            id: Date.now(),
            user: user?.username || 'Anonyme',
            avatar: user?.avatar || '',
            text,
            time: "À l'instant",
            likes: 0,
            likedBy: []
          };
          if (!debates[index].messages[msgIndex].replies) {
            debates[index].messages[msgIndex].replies = [];
          }
          debates[index].messages[msgIndex].replies.push(newReply);
          localStorage.setItem('pronobox_debates', JSON.stringify(debates));
          return newReply;
        }
      }
      throw new Error('Debate or message not found');
    }
    throw error;
  }
};

export const likeDebateMessage = async (debateId: string, messageId: string) => {
  try {
    const response = await api.post(`/debates/${debateId}/messages/${messageId}/like`);
    return response.data;
  } catch (error) {
    console.error('API Error:', error);
    throw error;
  }
};

export const likeDebateReply = async (debateId: string, messageId: string, replyId: string) => {
  try {
    const response = await api.post(`/debates/${debateId}/messages/${messageId}/replies/${replyId}/like`);
    return response.data;
  } catch (error) {
    console.error('API Error:', error);
    throw error;
  }
};

export const reactToProno = async (pronoId: string, emoji: string) => {
  try {
    const response = await api.post(`/pronos/${pronoId}/react`, { emoji });
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const user = JSON.parse(localStorage.getItem('fallbackUser') || 'null');
      const userId = user?.id || 'mock-id';
      
      const storageKey = `fallback_reactions_${pronoId}`;
      let reactions = JSON.parse(localStorage.getItem(storageKey) || '[]');
      
      let userExistingReactionEmoji = null;
      for (const r of reactions) {
        if (r.users && r.users.includes(userId)) {
          userExistingReactionEmoji = r.emoji;
          break;
        }
      }
      
      if (userExistingReactionEmoji === emoji) {
        // Toggle off
        reactions = reactions.map((r: any) => {
          if (r.emoji === emoji) {
            r.users = r.users.filter((uid: string) => uid !== userId);
          }
          return r;
        }).filter((r: any) => r.users.length > 0);
      } else {
        // Remove from old reaction if exists
        if (userExistingReactionEmoji) {
          reactions = reactions.map((r: any) => {
            if (r.emoji === userExistingReactionEmoji) {
              r.users = r.users.filter((uid: string) => uid !== userId);
            }
            return r;
          }).filter((r: any) => r.users.length > 0);
        }
        
        // Add to new reaction
        const targetReaction = reactions.find((r: any) => r.emoji === emoji);
        if (targetReaction) {
          targetReaction.users.push(userId);
        } else {
          reactions.push({ emoji, users: [userId] });
        }
      }
      
      localStorage.setItem(storageKey, JSON.stringify(reactions));
      return reactions;
    }
    throw error;
  }
};


// --- News/Actualites Services ---
export interface NewsArticle {
  id: string;
  title: string;
  description: string;
  link: string;
  image: string | null;
  source: string;
  sourceUrl?: string;
  pubDate: string;
  timestamp: number;
}

export const getActualites = async (): Promise<NewsArticle[]> => {
  try {
    const response = await api.get('/actualites');
    if (response.data && response.data.length > 0) {
      return response.data;
    }
  } catch (error) {
    console.error('Error fetching actualites:', error);
  }
  
  // Always return mock data if backend fails or returns empty array
  // so the UI can be tested.
  return [
    {
      id: 'mock-news-1',
      title: "Le PSG s'impose difficilement en Ligue des Champions",
      description: "Une victoire arrachée dans les dernières minutes de jeu permet aux Parisiens de prendre une option sur la qualification.",
      link: "https://www.lequipe.fr/Football/",
      image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
      source: "L'Équipe",
      pubDate: new Date().toISOString(),
      timestamp: Date.now()
    },
    {
      id: 'mock-news-2',
      title: "Real Madrid : Un nouveau prodige brésilien en approche",
      description: "Le club merengue a encore frappé fort sur le marché des transferts en sécurisant la signature d'un jeune talent très convoité.",
      link: "https://www.footmercato.net",
      image: "https://images.unsplash.com/photo-1518605368461-1ee7a30026e6?q=80&w=600&auto=format&fit=crop",
      source: "Footmercato",
      pubDate: new Date(Date.now() - 3600000).toISOString(),
      timestamp: Date.now() - 3600000
    },
    {
      id: 'mock-news-3',
      title: "L'équipe de France prépare son prochain match amical",
      description: "Didier Deschamps a dévoilé sa liste des 23 joueurs sélectionnés pour affronter l'Allemagne lors de la prochaine trêve internationale.",
      link: "https://www.eurosport.fr/football/",
      image: "https://images.unsplash.com/photo-1553775282-20af80779df7?q=80&w=600&auto=format&fit=crop",
      source: "Eurosport",
      pubDate: new Date(Date.now() - 7200000).toISOString(),
      timestamp: Date.now() - 7200000
    },
    {
      id: 'mock-news-4',
      title: "Barça : Lewandowski prolonge l'aventure en Catalogne",
      description: "L'attaquant polonais a signé un nouveau contrat de deux ans après des négociations intensives avec la direction barcelonaise.",
      link: "https://rmcsport.bfmtv.com/football/",
      image: "https://images.unsplash.com/photo-1579952362224-d986d4e219f7?q=80&w=600&auto=format&fit=crop",
      source: "RMC Sport",
      pubDate: new Date(Date.now() - 10800000).toISOString(),
      timestamp: Date.now() - 10800000
    },
    {
      id: 'mock-news-5',
      title: "Mercato : Arsenal cible un international français cet été",
      description: "Les Gunners préparent une offre de transfert colossale pour renforcer leur milieu de terrain avec un cadre de l'équipe de France.",
      link: "https://www.foot01.com",
      image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?q=80&w=600&auto=format&fit=crop",
      source: "Foot01",
      pubDate: new Date(Date.now() - 14400000).toISOString(),
      timestamp: Date.now() - 14400000
    },
    {
      id: 'mock-news-6',
      title: "Ballon d'Or : Les premiers favoris de l'année se dégagent",
      description: "Découvrez les joueurs qui mènent la danse dans les premiers pronostics de la presse spécialisée pour le prestigieux trophée individuel.",
      link: "https://www.francefootball.fr",
      image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
      source: "France Football",
      pubDate: new Date(Date.now() - 18000000).toISOString(),
      timestamp: Date.now() - 18000000
    },
    {
      id: 'mock-news-7',
      title: "Serie A : La Juventus vise le titre avec son nouvel entraîneur",
      description: "Les Bianconeri entament un nouveau chapitre de leur histoire avec de grandes ambitions tactiques et un recrutement ciblé.",
      link: "https://www.footmercato.net",
      image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=600&auto=format&fit=crop",
      source: "Footmercato",
      pubDate: new Date(Date.now() - 21600000).toISOString(),
      timestamp: Date.now() - 21600000
    },
    {
      id: 'mock-news-8',
      title: "Kylian Mbappé : 'Prêt à tout donner pour la nouvelle saison'",
      description: "L'attaquant vedette s'est confié longuement sur ses objectifs personnels et sa préparation physique pour les échéances à venir.",
      link: "https://www.lequipe.fr/Football/",
      image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=600&auto=format&fit=crop",
      source: "L'Équipe",
      pubDate: new Date(Date.now() - 25200000).toISOString(),
      timestamp: Date.now() - 25200000
    },
    {
      id: 'mock-news-9',
      title: "Ligue 1 : Marseille et Lyon dos à dos après un choc spectaculaire",
      description: "L'Olympico a tenu toutes ses promesses au terme d'un match sous haute tension, riche en buts et en rebondissements tactiques.",
      link: "https://sports.fr",
      image: "https://images.unsplash.com/photo-1543351611-58f69d7c1781?q=80&w=600&auto=format&fit=crop",
      source: "Sports.fr",
      pubDate: new Date(Date.now() - 28800000).toISOString(),
      timestamp: Date.now() - 28800000
    },
    {
      id: 'mock-news-10',
      title: "Ligue des Champions : Le tirage au sort complet de la phase de poules",
      description: "Découvrez toutes les affiches de la phase de ligue de cette édition historique, promettant des chocs monumentaux dès l'automne.",
      link: "https://www.eurosport.fr/football/",
      image: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=600&auto=format&fit=crop",
      source: "Eurosport",
      pubDate: new Date(Date.now() - 32400000).toISOString(),
      timestamp: Date.now() - 32400000
    }
  ];
};

export const favoriteDebate = async (id: string | number) => {
  try {
    const response = await api.post(`/debates/${id}/favorite`);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const user = JSON.parse(localStorage.getItem('fallbackUser') || 'null');
      const userId = user?.id || '1';
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const index = debates.findIndex((d: Debate) => String(d.id) === String(id) || String(d._id) === String(id));
      if (index !== -1) {
        const debate = debates[index];
        if (!debate.favoritedBy) {
          debate.favoritedBy = [];
        }
        const userIndex = debate.favoritedBy.findIndex((uid: any) => String(uid) === String(userId));
        if (userIndex === -1) {
          debate.favoritedBy.push(userId);
        } else {
          debate.favoritedBy.splice(userIndex, 1);
        }
        if (debate.favoritedBy.length > 0) {
          debate.isFavorite = true;
          debate.expiresAt = null;
        } else {
          debate.isFavorite = false;
          debate.expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
        }
        localStorage.setItem('pronobox_debates', JSON.stringify(debates));
        return debate;
      }
      throw new Error('Debate not found');
    }
    throw error;
  }
};

export const deleteDebateMessage = async (debateId: string | number, messageId: string | number) => {
  try {
    const response = await api.delete(`/debates/${debateId}/messages/${messageId}`);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const index = debates.findIndex((d: Debate) => String(d.id) === String(debateId) || String(d._id) === String(debateId));
      if (index !== -1) {
        const debate = debates[index];
        debate.messages = (debate.messages || []).filter((m: any) => String(m.id || m._id) !== String(messageId));
        localStorage.setItem('pronobox_debates', JSON.stringify(debates));
        return debate;
      }
      throw new Error('Debate not found');
    }
    throw error;
  }
};

export const deleteDebateReply = async (debateId: string | number, messageId: string | number, replyId: string | number) => {
  try {
    const response = await api.delete(`/debates/${debateId}/messages/${messageId}/replies/${replyId}`);
    return response.data;
  } catch (error) {
    if (localStorage.getItem('fallbackMode') === 'true') {
      const debates = JSON.parse(localStorage.getItem('pronobox_debates') || '[]');
      const index = debates.findIndex((d: Debate) => String(d.id) === String(debateId) || String(d._id) === String(debateId));
      if (index !== -1) {
        const debate = debates[index];
        debate.messages = (debate.messages || []).map((m: any) => {
          if (String(m.id || m._id) === String(messageId)) {
            m.replies = (m.replies || []).filter((r: any) => String(r.id || r._id) !== String(replyId));
          }
          return m;
        });
        localStorage.setItem('pronobox_debates', JSON.stringify(debates));
        return debate;
      }
      throw new Error('Debate not found');
    }
    throw error;
  }
};

export default api;
